/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOCOL_PB_H_INCLUDED
#define PB_PROTOCOL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Message_Type {
    Message_Type_AUTH_INIT = 0,
    Message_Type_AUTH_CHALLENGE = 1,
    Message_Type_AUTH_RESPONSE = 2,
    Message_Type_AUTH_RESULT = 3,
    Message_Type_RANGE_PROOF_REQUEST = 4,
    Message_Type_RANGE_PROOF_RESULT = 5
} Message_Type;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) AuthInit_signature_t;
/* 1. Client -> Server: Start Auth */
typedef struct _AuthInit {
    char serial_id[64]; /* Client Serial ID */
    AuthInit_signature_t signature; /* Signature of SHA256(serial_id) */
} AuthInit;

typedef PB_BYTES_ARRAY_T(32) AuthChallenge_random_number_t;
typedef PB_BYTES_ARRAY_T(64) AuthChallenge_signature_t;
/* 2. Server -> Client: Challenge */
typedef struct _AuthChallenge {
    AuthChallenge_random_number_t random_number; /* 32 bytes random */
    AuthChallenge_signature_t signature; /* Server signature of random_number */
} AuthChallenge;

typedef PB_BYTES_ARRAY_T(64) AuthResponse_signature_t;
/* 3. Client -> Server: Respond to Challenge */
typedef struct _AuthResponse {
    AuthResponse_signature_t signature; /* Client signature of random_number */
} AuthResponse;

/* 4. Server -> Client: Result */
typedef struct _AuthResult {
    bool success;
} AuthResult;

typedef PB_BYTES_ARRAY_T(65) RangeProofRequest_c0_t;
typedef PB_BYTES_ARRAY_T(65) RangeProofRequest_c1_t;
typedef PB_BYTES_ARRAY_T(65) RangeProofRequest_c2_t;
typedef PB_BYTES_ARRAY_T(65) RangeProofRequest_c3_t;
typedef PB_BYTES_ARRAY_T(65) RangeProofRequest_range_c1_t;
typedef PB_BYTES_ARRAY_T(65) RangeProofRequest_range_c2_t;
/* 5. Client -> Server: Range Proof */
typedef struct _RangeProofRequest {
    /* Range parameters */
    uint64_t min_value;
    uint64_t max_value;
    uint32_t bit_length;
    /* Commitments for 4-square representation: C0..C3
 Each commitment is a point (x, y) on the curve. 
 Compressed point is 33 bytes. Uncompressed 65 bytes.
 We will use raw bytes for simplicity or coordinate pairs.
 Nanopb is easiest with bytes. */
    RangeProofRequest_c0_t c0; /* Commitment C0 */
    RangeProofRequest_c1_t c1; /* Commitment C1 */
    RangeProofRequest_c2_t c2; /* Commitment C2 */
    RangeProofRequest_c3_t c3; /* Commitment C3 */
    /* Range Proof commitments: c_1, c_2 */
    RangeProofRequest_range_c1_t range_c1;
    RangeProofRequest_range_c2_t range_c2;
} RangeProofRequest;

/* 6. Server -> Client: Result */
typedef struct _RangeProofResult {
    bool success;
} RangeProofResult;

/* Wrapper for all messages */
typedef struct _Message {
    Message_Type type;
    pb_size_t which_payload;
    union _Message_payload {
        AuthInit auth_init;
        AuthChallenge auth_challenge;
        AuthResponse auth_response;
        AuthResult auth_result;
        RangeProofRequest range_proof_request;
        RangeProofResult range_proof_result;
    } payload;
} Message;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Message_Type_MIN Message_Type_AUTH_INIT
#define _Message_Type_MAX Message_Type_RANGE_PROOF_RESULT
#define _Message_Type_ARRAYSIZE ((Message_Type)(Message_Type_RANGE_PROOF_RESULT+1))

#define Message_type_ENUMTYPE Message_Type








/* Initializer values for message structs */
#define Message_init_default                     {_Message_Type_MIN, 0, {AuthInit_init_default}}
#define AuthInit_init_default                    {"", {0, {0}}}
#define AuthChallenge_init_default               {{0, {0}}, {0, {0}}}
#define AuthResponse_init_default                {{0, {0}}}
#define AuthResult_init_default                  {0}
#define RangeProofRequest_init_default           {0, 0, 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}
#define RangeProofResult_init_default            {0}
#define Message_init_zero                        {_Message_Type_MIN, 0, {AuthInit_init_zero}}
#define AuthInit_init_zero                       {"", {0, {0}}}
#define AuthChallenge_init_zero                  {{0, {0}}, {0, {0}}}
#define AuthResponse_init_zero                   {{0, {0}}}
#define AuthResult_init_zero                     {0}
#define RangeProofRequest_init_zero              {0, 0, 0, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}, {0, {0}}}
#define RangeProofResult_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define AuthInit_serial_id_tag                   1
#define AuthInit_signature_tag                   2
#define AuthChallenge_random_number_tag          1
#define AuthChallenge_signature_tag              2
#define AuthResponse_signature_tag               1
#define AuthResult_success_tag                   1
#define RangeProofRequest_min_value_tag          1
#define RangeProofRequest_max_value_tag          2
#define RangeProofRequest_bit_length_tag         3
#define RangeProofRequest_c0_tag                 4
#define RangeProofRequest_c1_tag                 5
#define RangeProofRequest_c2_tag                 6
#define RangeProofRequest_c3_tag                 7
#define RangeProofRequest_range_c1_tag           8
#define RangeProofRequest_range_c2_tag           9
#define RangeProofResult_success_tag             1
#define Message_type_tag                         1
#define Message_auth_init_tag                    2
#define Message_auth_challenge_tag               3
#define Message_auth_response_tag                4
#define Message_auth_result_tag                  5
#define Message_range_proof_request_tag          6
#define Message_range_proof_result_tag           7

/* Struct field encoding specification for nanopb */
#define Message_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_init,payload.auth_init),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_challenge,payload.auth_challenge),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_response,payload.auth_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_result,payload.auth_result),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,range_proof_request,payload.range_proof_request),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,range_proof_result,payload.range_proof_result),   7)
#define Message_CALLBACK NULL
#define Message_DEFAULT NULL
#define Message_payload_auth_init_MSGTYPE AuthInit
#define Message_payload_auth_challenge_MSGTYPE AuthChallenge
#define Message_payload_auth_response_MSGTYPE AuthResponse
#define Message_payload_auth_result_MSGTYPE AuthResult
#define Message_payload_range_proof_request_MSGTYPE RangeProofRequest
#define Message_payload_range_proof_result_MSGTYPE RangeProofResult

#define AuthInit_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   serial_id,         1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2)
#define AuthInit_CALLBACK NULL
#define AuthInit_DEFAULT NULL

#define AuthChallenge_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    random_number,     1) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         2)
#define AuthChallenge_CALLBACK NULL
#define AuthChallenge_DEFAULT NULL

#define AuthResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    signature,         1)
#define AuthResponse_CALLBACK NULL
#define AuthResponse_DEFAULT NULL

#define AuthResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define AuthResult_CALLBACK NULL
#define AuthResult_DEFAULT NULL

#define RangeProofRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   min_value,         1) \
X(a, STATIC,   SINGULAR, UINT64,   max_value,         2) \
X(a, STATIC,   SINGULAR, UINT32,   bit_length,        3) \
X(a, STATIC,   SINGULAR, BYTES,    c0,                4) \
X(a, STATIC,   SINGULAR, BYTES,    c1,                5) \
X(a, STATIC,   SINGULAR, BYTES,    c2,                6) \
X(a, STATIC,   SINGULAR, BYTES,    c3,                7) \
X(a, STATIC,   SINGULAR, BYTES,    range_c1,          8) \
X(a, STATIC,   SINGULAR, BYTES,    range_c2,          9)
#define RangeProofRequest_CALLBACK NULL
#define RangeProofRequest_DEFAULT NULL

#define RangeProofResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1)
#define RangeProofResult_CALLBACK NULL
#define RangeProofResult_DEFAULT NULL

extern const pb_msgdesc_t Message_msg;
extern const pb_msgdesc_t AuthInit_msg;
extern const pb_msgdesc_t AuthChallenge_msg;
extern const pb_msgdesc_t AuthResponse_msg;
extern const pb_msgdesc_t AuthResult_msg;
extern const pb_msgdesc_t RangeProofRequest_msg;
extern const pb_msgdesc_t RangeProofResult_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Message_fields &Message_msg
#define AuthInit_fields &AuthInit_msg
#define AuthChallenge_fields &AuthChallenge_msg
#define AuthResponse_fields &AuthResponse_msg
#define AuthResult_fields &AuthResult_msg
#define RangeProofRequest_fields &RangeProofRequest_msg
#define RangeProofResult_fields &RangeProofResult_msg

/* Maximum encoded size of messages (where known) */
#define AuthChallenge_size                       100
#define AuthInit_size                            131
#define AuthResponse_size                        66
#define AuthResult_size                          2
#define Message_size                             435
#define PROTOCOL_PB_H_MAX_SIZE                   Message_size
#define RangeProofRequest_size                   430
#define RangeProofResult_size                    2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
