/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protocol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message, Message, AUTO)


PB_BIND(AuthInit, AuthInit, AUTO)


PB_BIND(AuthChallenge, AuthChallenge, AUTO)


PB_BIND(AuthResponse, AuthResponse, AUTO)


PB_BIND(AuthResult, AuthResult, AUTO)


PB_BIND(RangeProofRequest, RangeProofRequest, AUTO)


PB_BIND(RangeProofResult, RangeProofResult, AUTO)





